### PR TITLE
Accept UTF-8 string

### PR DESCRIPTION
**Pull request by kuroda**
This should solve #10

### CODE REVIEW

**Comment by kuroda** [comment]
@danlucraft 

I found a fault in my commits. I will send a revised pull request later.

**Comment by kuroda** [comment]
@danlucraft 

Please have a look if you have leisure time!

**Comment by danlucraft** [comment]
I pushed a commit to force the encoding of the Regex to ASCII-8BIT instead. Can you check it and see if it works for you before I release a new version? 

The commit is https://github.com/danlucraft/rak/commit/1abc4fc7eedf37edad238b37b00dd6fc921c2be2

**Comment by kuroda** [comment]
@danlucraft 

I confirmed that I can search a UTF-8 string with your commit. Thank you very much!

**Comment by danlucraft** [comment]
Good then! I released a new version of the gem with this in. (1.4)

**Pull request closed without merging**
